import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import DefaultLayout from "../components/layouts/default";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Link href={`/c/11`}>
          <h2>Note 11</h2>
        </Link>
      </DefaultLayout>
    </>
  );
}
